In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [15]:
df = pd.read_csv("features.csv",header=None)
df.head()

           0         1         2    3     4     5
0  16.383183  0.712812  1.519675 -3.0  7.71  7.60
1  19.761131  0.676551  1.590439 -3.0  8.10  7.31
2  21.905021  0.709740  1.557257 -3.0  8.58  7.54
3  18.421522  0.682352  1.597724 -3.0  4.94  6.01
4  12.420507  0.751094  1.459101 -3.0  6.96  3.92

In [16]:
data = np.array(df)
data.shape

(1280, 6)

In [17]:
val = []
for i in range(data.shape[0]):
    lst = []
    for j in range(6):
       if(j<4): 
        lst.append(data[i][j])
       else:
        if(data[i][j]<=4):   
         lst.append(0)
        else:
         lst.append(1)
    val.append(lst)

In [18]:
arr = np.array(val)

In [19]:
arr.shape

(1280, 6)

In [20]:
df = pd.DataFrame(arr)
df.columns = ["Activity","Mobility","Complexity","NSI","Valence","Arousal"]
df.head(40)

     Activity  Mobility  Complexity  NSI  Valence  Arousal
0   16.383183  0.712812    1.519675 -3.0      1.0      1.0
1   19.761131  0.676551    1.590439 -3.0      1.0      1.0
2   21.905021  0.709740    1.557257 -3.0      1.0      1.0
3   18.421522  0.682352    1.597724 -3.0      1.0      1.0
4   12.420507  0.751094    1.459101 -3.0      1.0      0.0
5   16.219186  0.716332    1.547856 -3.0      1.0      0.0
6   21.172450  0.690756    1.573431 -3.0      1.0      0.0
7   23.226636  0.662702    1.592356 -3.0      1.0      0.0
8   26.045377  0.660348    1.614725 -3.0      1.0      0.0
9   18.383285  0.709157    1.539146 -3.0      0.0      1.0
10  21.056996  0.673728    1.601543 -3.0      0.0      0.0
11  20.355092  0.682126    1.527919 -3.0      0.0      0.0
12  24.155746  0.690452    1.648246 -3.0      0.0      0.0
13  23.924021  0.700566    1.641058 -3.0      1.0      0.0
14  18.134070  0.686843    1.554180 -3.0      0.0      1.0
15  16.228482  0.722927    1.535725 -3.0      1.0      1.0
16  15.097112  0.721230    1.512287 -3.0      0.0      1.0
17  15.122317  0.704867    1.545059 -3.0      1.0      1.0
18  20.085228  0.671985    1.584036 -3.0      1.0      1.0
19  18.898110  0.716741    1.580966 -3.0      1.0      1.0
20  22.103885  0.667445    1.607969 -3.0      1.0      1.0
21  19.282700  0.696686    1.562846 -3.0      1.0      0.0
22  18.713816  0.719251    1.511478 -3.0      1.0      0.0
23  16.506791  0.714169    1.524234 -3.0      1.0      1.0
24  21.755323  0.677182    1.556676 -3.0      1.0      1.0
25  29.234205  0.868241    1.477777 -3.0      1.0      1.0
26  24.178728  0.723452    1.581369 -3.0      1.0      1.0
27  20.473273  0.672867    1.564895 -3.0      0.0      0.0
28  15.084241  0.724299    1.497656 -3.0      0.0      0.0
29  20.690531  0.696586    1.569850 -3.0      0.0      0.0
30  14.854181  0.761977    1.500630 -3.0      0.0      1.0
31  19.704123  0.675807    1.516368 -3.0      0.0      1.0
32  22.425707  0.748116    1.570314 -3.0      0.0      0.0
33  19.398446  0.710849    1.539892 -3.0      0.0      1.0
34  16.882927  0.722965    1.555444 -3.0      0.0      1.0
35  21.016266  0.691668    1.576681 -3.0      0.0      1.0
36  22.356478  0.673059    1.567637 -3.0      0.0      1.0
37  18.709146  0.687104    1.557956 -3.0      0.0      1.0
38  15.978282  0.742741    1.511608 -3.0      0.0      1.0
39  14.948352  0.745767    1.484812 -3.0      1.0      1.0

In [21]:
df.to_csv('features_new.csv', header=False, index=False)

In [22]:
from sklearn.preprocessing import MinMaxScaler

In [23]:
scaler = MinMaxScaler()

In [24]:
n_df = df
n_df.head()

    Activity  Mobility  Complexity  NSI  Valence  Arousal
0  16.383183  0.712812    1.519675 -3.0      1.0      1.0
1  19.761131  0.676551    1.590439 -3.0      1.0      1.0
2  21.905021  0.709740    1.557257 -3.0      1.0      1.0
3  18.421522  0.682352    1.597724 -3.0      1.0      1.0
4  12.420507  0.751094    1.459101 -3.0      1.0      0.0

In [25]:
n_df = pd.DataFrame(scaler.fit_transform(n_df))

In [26]:
n_df.head()
n_df.columns = ["Activity","Mobility","Complexity","NSI","Valence","Arousal"]

In [27]:
n_df.to_csv('features_normalized.csv', header=False, index=False)